version: 2.1
jobs:
    build:
        working_directory: ~/demo-cicd-backend
        docker:
            -   image: circleci/openjdk:8-jdk-stretch
        steps:
            - checkout
            -   restore_cache:
                    key: demo-cicd-backend-{{ checksum "pom.xml" }}
            -   run: mvn dependency:go-offline
            -   save_cache:
                    paths:
                        - ~/.m2
                    key: demo-cicd-backend-{{ checksum "pom.xml" }}
            -   run: mvn package
orbs:
    maven: circleci/maven@0.0.12
    heroku: circleci/heroku@1.0.1
workflows:
    version: 2
    maven_test:
        jobs:
            - maven/test